# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adriano/Projects/jme3/opensteer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adriano/Projects/jme3/opensteer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adriano/Projects/jme3/opensteer/CMakeFiles /home/adriano/Projects/jme3/opensteer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adriano/Projects/jme3/opensteer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named opensteer

# Build rule for target.
opensteer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opensteer
.PHONY : opensteer

# fast build rule for target.
opensteer/fast:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/build
.PHONY : opensteer/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) -f example/CMakeFiles/example.dir/build.make example/CMakeFiles/example.dir/build
.PHONY : example/fast

src/Clock.o: src/Clock.cpp.o
.PHONY : src/Clock.o

# target to build an object file
src/Clock.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Clock.cpp.o
.PHONY : src/Clock.cpp.o

src/Clock.i: src/Clock.cpp.i
.PHONY : src/Clock.i

# target to preprocess a source file
src/Clock.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Clock.cpp.i
.PHONY : src/Clock.cpp.i

src/Clock.s: src/Clock.cpp.s
.PHONY : src/Clock.s

# target to generate assembly for a file
src/Clock.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Clock.cpp.s
.PHONY : src/Clock.cpp.s

src/Color.o: src/Color.cpp.o
.PHONY : src/Color.o

# target to build an object file
src/Color.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Color.cpp.o
.PHONY : src/Color.cpp.o

src/Color.i: src/Color.cpp.i
.PHONY : src/Color.i

# target to preprocess a source file
src/Color.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Color.cpp.i
.PHONY : src/Color.cpp.i

src/Color.s: src/Color.cpp.s
.PHONY : src/Color.s

# target to generate assembly for a file
src/Color.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Color.cpp.s
.PHONY : src/Color.cpp.s

src/Obstacle.o: src/Obstacle.cpp.o
.PHONY : src/Obstacle.o

# target to build an object file
src/Obstacle.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Obstacle.cpp.o
.PHONY : src/Obstacle.cpp.o

src/Obstacle.i: src/Obstacle.cpp.i
.PHONY : src/Obstacle.i

# target to preprocess a source file
src/Obstacle.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Obstacle.cpp.i
.PHONY : src/Obstacle.cpp.i

src/Obstacle.s: src/Obstacle.cpp.s
.PHONY : src/Obstacle.s

# target to generate assembly for a file
src/Obstacle.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Obstacle.cpp.s
.PHONY : src/Obstacle.cpp.s

src/OldPathway.o: src/OldPathway.cpp.o
.PHONY : src/OldPathway.o

# target to build an object file
src/OldPathway.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/OldPathway.cpp.o
.PHONY : src/OldPathway.cpp.o

src/OldPathway.i: src/OldPathway.cpp.i
.PHONY : src/OldPathway.i

# target to preprocess a source file
src/OldPathway.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/OldPathway.cpp.i
.PHONY : src/OldPathway.cpp.i

src/OldPathway.s: src/OldPathway.cpp.s
.PHONY : src/OldPathway.s

# target to generate assembly for a file
src/OldPathway.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/OldPathway.cpp.s
.PHONY : src/OldPathway.cpp.s

src/Path.o: src/Path.cpp.o
.PHONY : src/Path.o

# target to build an object file
src/Path.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Path.cpp.o
.PHONY : src/Path.cpp.o

src/Path.i: src/Path.cpp.i
.PHONY : src/Path.i

# target to preprocess a source file
src/Path.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Path.cpp.i
.PHONY : src/Path.cpp.i

src/Path.s: src/Path.cpp.s
.PHONY : src/Path.s

# target to generate assembly for a file
src/Path.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Path.cpp.s
.PHONY : src/Path.cpp.s

src/Pathway.o: src/Pathway.cpp.o
.PHONY : src/Pathway.o

# target to build an object file
src/Pathway.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Pathway.cpp.o
.PHONY : src/Pathway.cpp.o

src/Pathway.i: src/Pathway.cpp.i
.PHONY : src/Pathway.i

# target to preprocess a source file
src/Pathway.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Pathway.cpp.i
.PHONY : src/Pathway.cpp.i

src/Pathway.s: src/Pathway.cpp.s
.PHONY : src/Pathway.s

# target to generate assembly for a file
src/Pathway.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Pathway.cpp.s
.PHONY : src/Pathway.cpp.s

src/PlugIn.o: src/PlugIn.cpp.o
.PHONY : src/PlugIn.o

# target to build an object file
src/PlugIn.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/PlugIn.cpp.o
.PHONY : src/PlugIn.cpp.o

src/PlugIn.i: src/PlugIn.cpp.i
.PHONY : src/PlugIn.i

# target to preprocess a source file
src/PlugIn.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/PlugIn.cpp.i
.PHONY : src/PlugIn.cpp.i

src/PlugIn.s: src/PlugIn.cpp.s
.PHONY : src/PlugIn.s

# target to generate assembly for a file
src/PlugIn.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/PlugIn.cpp.s
.PHONY : src/PlugIn.cpp.s

src/PolylineSegmentedPath.o: src/PolylineSegmentedPath.cpp.o
.PHONY : src/PolylineSegmentedPath.o

# target to build an object file
src/PolylineSegmentedPath.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/PolylineSegmentedPath.cpp.o
.PHONY : src/PolylineSegmentedPath.cpp.o

src/PolylineSegmentedPath.i: src/PolylineSegmentedPath.cpp.i
.PHONY : src/PolylineSegmentedPath.i

# target to preprocess a source file
src/PolylineSegmentedPath.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/PolylineSegmentedPath.cpp.i
.PHONY : src/PolylineSegmentedPath.cpp.i

src/PolylineSegmentedPath.s: src/PolylineSegmentedPath.cpp.s
.PHONY : src/PolylineSegmentedPath.s

# target to generate assembly for a file
src/PolylineSegmentedPath.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/PolylineSegmentedPath.cpp.s
.PHONY : src/PolylineSegmentedPath.cpp.s

src/PolylineSegmentedPathwaySegmentRadii.o: src/PolylineSegmentedPathwaySegmentRadii.cpp.o
.PHONY : src/PolylineSegmentedPathwaySegmentRadii.o

# target to build an object file
src/PolylineSegmentedPathwaySegmentRadii.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/PolylineSegmentedPathwaySegmentRadii.cpp.o
.PHONY : src/PolylineSegmentedPathwaySegmentRadii.cpp.o

src/PolylineSegmentedPathwaySegmentRadii.i: src/PolylineSegmentedPathwaySegmentRadii.cpp.i
.PHONY : src/PolylineSegmentedPathwaySegmentRadii.i

# target to preprocess a source file
src/PolylineSegmentedPathwaySegmentRadii.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/PolylineSegmentedPathwaySegmentRadii.cpp.i
.PHONY : src/PolylineSegmentedPathwaySegmentRadii.cpp.i

src/PolylineSegmentedPathwaySegmentRadii.s: src/PolylineSegmentedPathwaySegmentRadii.cpp.s
.PHONY : src/PolylineSegmentedPathwaySegmentRadii.s

# target to generate assembly for a file
src/PolylineSegmentedPathwaySegmentRadii.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/PolylineSegmentedPathwaySegmentRadii.cpp.s
.PHONY : src/PolylineSegmentedPathwaySegmentRadii.cpp.s

src/PolylineSegmentedPathwaySingleRadius.o: src/PolylineSegmentedPathwaySingleRadius.cpp.o
.PHONY : src/PolylineSegmentedPathwaySingleRadius.o

# target to build an object file
src/PolylineSegmentedPathwaySingleRadius.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/PolylineSegmentedPathwaySingleRadius.cpp.o
.PHONY : src/PolylineSegmentedPathwaySingleRadius.cpp.o

src/PolylineSegmentedPathwaySingleRadius.i: src/PolylineSegmentedPathwaySingleRadius.cpp.i
.PHONY : src/PolylineSegmentedPathwaySingleRadius.i

# target to preprocess a source file
src/PolylineSegmentedPathwaySingleRadius.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/PolylineSegmentedPathwaySingleRadius.cpp.i
.PHONY : src/PolylineSegmentedPathwaySingleRadius.cpp.i

src/PolylineSegmentedPathwaySingleRadius.s: src/PolylineSegmentedPathwaySingleRadius.cpp.s
.PHONY : src/PolylineSegmentedPathwaySingleRadius.s

# target to generate assembly for a file
src/PolylineSegmentedPathwaySingleRadius.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/PolylineSegmentedPathwaySingleRadius.cpp.s
.PHONY : src/PolylineSegmentedPathwaySingleRadius.cpp.s

src/SegmentedPath.o: src/SegmentedPath.cpp.o
.PHONY : src/SegmentedPath.o

# target to build an object file
src/SegmentedPath.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/SegmentedPath.cpp.o
.PHONY : src/SegmentedPath.cpp.o

src/SegmentedPath.i: src/SegmentedPath.cpp.i
.PHONY : src/SegmentedPath.i

# target to preprocess a source file
src/SegmentedPath.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/SegmentedPath.cpp.i
.PHONY : src/SegmentedPath.cpp.i

src/SegmentedPath.s: src/SegmentedPath.cpp.s
.PHONY : src/SegmentedPath.s

# target to generate assembly for a file
src/SegmentedPath.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/SegmentedPath.cpp.s
.PHONY : src/SegmentedPath.cpp.s

src/SegmentedPathway.o: src/SegmentedPathway.cpp.o
.PHONY : src/SegmentedPathway.o

# target to build an object file
src/SegmentedPathway.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/SegmentedPathway.cpp.o
.PHONY : src/SegmentedPathway.cpp.o

src/SegmentedPathway.i: src/SegmentedPathway.cpp.i
.PHONY : src/SegmentedPathway.i

# target to preprocess a source file
src/SegmentedPathway.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/SegmentedPathway.cpp.i
.PHONY : src/SegmentedPathway.cpp.i

src/SegmentedPathway.s: src/SegmentedPathway.cpp.s
.PHONY : src/SegmentedPathway.s

# target to generate assembly for a file
src/SegmentedPathway.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/SegmentedPathway.cpp.s
.PHONY : src/SegmentedPathway.cpp.s

src/SimpleVehicle.o: src/SimpleVehicle.cpp.o
.PHONY : src/SimpleVehicle.o

# target to build an object file
src/SimpleVehicle.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/SimpleVehicle.cpp.o
.PHONY : src/SimpleVehicle.cpp.o

src/SimpleVehicle.i: src/SimpleVehicle.cpp.i
.PHONY : src/SimpleVehicle.i

# target to preprocess a source file
src/SimpleVehicle.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/SimpleVehicle.cpp.i
.PHONY : src/SimpleVehicle.cpp.i

src/SimpleVehicle.s: src/SimpleVehicle.cpp.s
.PHONY : src/SimpleVehicle.s

# target to generate assembly for a file
src/SimpleVehicle.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/SimpleVehicle.cpp.s
.PHONY : src/SimpleVehicle.cpp.s

src/TerrainRayTest.o: src/TerrainRayTest.cpp.o
.PHONY : src/TerrainRayTest.o

# target to build an object file
src/TerrainRayTest.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/TerrainRayTest.cpp.o
.PHONY : src/TerrainRayTest.cpp.o

src/TerrainRayTest.i: src/TerrainRayTest.cpp.i
.PHONY : src/TerrainRayTest.i

# target to preprocess a source file
src/TerrainRayTest.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/TerrainRayTest.cpp.i
.PHONY : src/TerrainRayTest.cpp.i

src/TerrainRayTest.s: src/TerrainRayTest.cpp.s
.PHONY : src/TerrainRayTest.s

# target to generate assembly for a file
src/TerrainRayTest.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/TerrainRayTest.cpp.s
.PHONY : src/TerrainRayTest.cpp.s

src/Vec3.o: src/Vec3.cpp.o
.PHONY : src/Vec3.o

# target to build an object file
src/Vec3.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Vec3.cpp.o
.PHONY : src/Vec3.cpp.o

src/Vec3.i: src/Vec3.cpp.i
.PHONY : src/Vec3.i

# target to preprocess a source file
src/Vec3.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Vec3.cpp.i
.PHONY : src/Vec3.cpp.i

src/Vec3.s: src/Vec3.cpp.s
.PHONY : src/Vec3.s

# target to generate assembly for a file
src/Vec3.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Vec3.cpp.s
.PHONY : src/Vec3.cpp.s

src/Vec3Utilities.o: src/Vec3Utilities.cpp.o
.PHONY : src/Vec3Utilities.o

# target to build an object file
src/Vec3Utilities.cpp.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Vec3Utilities.cpp.o
.PHONY : src/Vec3Utilities.cpp.o

src/Vec3Utilities.i: src/Vec3Utilities.cpp.i
.PHONY : src/Vec3Utilities.i

# target to preprocess a source file
src/Vec3Utilities.cpp.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Vec3Utilities.cpp.i
.PHONY : src/Vec3Utilities.cpp.i

src/Vec3Utilities.s: src/Vec3Utilities.cpp.s
.PHONY : src/Vec3Utilities.s

# target to generate assembly for a file
src/Vec3Utilities.cpp.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/Vec3Utilities.cpp.s
.PHONY : src/Vec3Utilities.cpp.s

src/lq.o: src/lq.c.o
.PHONY : src/lq.o

# target to build an object file
src/lq.c.o:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/lq.c.o
.PHONY : src/lq.c.o

src/lq.i: src/lq.c.i
.PHONY : src/lq.i

# target to preprocess a source file
src/lq.c.i:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/lq.c.i
.PHONY : src/lq.c.i

src/lq.s: src/lq.c.s
.PHONY : src/lq.s

# target to generate assembly for a file
src/lq.c.s:
	$(MAKE) -f CMakeFiles/opensteer.dir/build.make CMakeFiles/opensteer.dir/src/lq.c.s
.PHONY : src/lq.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... opensteer"
	@echo "... rebuild_cache"
	@echo "... example"
	@echo "... src/Clock.o"
	@echo "... src/Clock.i"
	@echo "... src/Clock.s"
	@echo "... src/Color.o"
	@echo "... src/Color.i"
	@echo "... src/Color.s"
	@echo "... src/Obstacle.o"
	@echo "... src/Obstacle.i"
	@echo "... src/Obstacle.s"
	@echo "... src/OldPathway.o"
	@echo "... src/OldPathway.i"
	@echo "... src/OldPathway.s"
	@echo "... src/Path.o"
	@echo "... src/Path.i"
	@echo "... src/Path.s"
	@echo "... src/Pathway.o"
	@echo "... src/Pathway.i"
	@echo "... src/Pathway.s"
	@echo "... src/PlugIn.o"
	@echo "... src/PlugIn.i"
	@echo "... src/PlugIn.s"
	@echo "... src/PolylineSegmentedPath.o"
	@echo "... src/PolylineSegmentedPath.i"
	@echo "... src/PolylineSegmentedPath.s"
	@echo "... src/PolylineSegmentedPathwaySegmentRadii.o"
	@echo "... src/PolylineSegmentedPathwaySegmentRadii.i"
	@echo "... src/PolylineSegmentedPathwaySegmentRadii.s"
	@echo "... src/PolylineSegmentedPathwaySingleRadius.o"
	@echo "... src/PolylineSegmentedPathwaySingleRadius.i"
	@echo "... src/PolylineSegmentedPathwaySingleRadius.s"
	@echo "... src/SegmentedPath.o"
	@echo "... src/SegmentedPath.i"
	@echo "... src/SegmentedPath.s"
	@echo "... src/SegmentedPathway.o"
	@echo "... src/SegmentedPathway.i"
	@echo "... src/SegmentedPathway.s"
	@echo "... src/SimpleVehicle.o"
	@echo "... src/SimpleVehicle.i"
	@echo "... src/SimpleVehicle.s"
	@echo "... src/TerrainRayTest.o"
	@echo "... src/TerrainRayTest.i"
	@echo "... src/TerrainRayTest.s"
	@echo "... src/Vec3.o"
	@echo "... src/Vec3.i"
	@echo "... src/Vec3.s"
	@echo "... src/Vec3Utilities.o"
	@echo "... src/Vec3Utilities.i"
	@echo "... src/Vec3Utilities.s"
	@echo "... src/lq.o"
	@echo "... src/lq.i"
	@echo "... src/lq.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

